controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

app_number101:
    path: /lucky/number101
    controller: App\Controller\LuckyController::number2

blog_list:
    path: /blog
    controller: App\Controller\BlogController::list